### ISSUE TITLE
Cannot find module error when using `svelte-as-markup-preprocessor` in SvelteKit

### ISSUE THREAD

**Issue by AradAral** [micantoine/svelte-preprocess-cssmodules#38]
Hi there. Great project, something like this was very much needed in the Svelte ecosystem, I hope this repo gets more and more pouplar.

I'm using SvelteKit (v1.0.0-next.201) 

## Steps to reproduce:
1. Create a fresh new SvelteKit project: `npm init svelte@next`.
2. Run `npm install` to install the initial packages
2. Install both "svelte-preprocess-cssmodules" and "svelte-as-markup-preprocessor": `npm i -D svelte-preprocess-cssmodules svelte-as-markup-preprocessor`.
3. Modify the `svelte.config.js` file so that it looks like so:
```js
import sveltePreprocess from 'svelte-preprocess';
import cssModulesPreprocess from 'svelte-preprocess-cssmodules';
import { asMarkupPreprocessor } from 'svelte-as-markup-preprocessor';

const config = {
    preprocess: [
        asMarkupPreprocessor([
            sveltePreprocess()
        ]),
        cssModulesPreprocess()
    ],

    // rest of config...
};
```
4. Run the project: `npm run dev`
5. Take a look at the console and you'll see the following error:
```
Cannot find module 'C:\Users\Arad\Desktop\CSSModulesFresh\node_modules\svelte-as-markup-preprocessor\out\esm\index.js' imported from C:\Users\Arad\Desktop\CSSModulesFresh\svelte.config.js
Did you mean to import svelte-as-markup-preprocessor/out/cjs/index.js?
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\Arad\Desktop\CSSModulesFresh\node_modules\svelte-as-markup-preprocessor\out\esm\index.js' imported from C:\Users\Arad\Desktop\CSSModulesFresh\svelte.config.js
Did you mean to import svelte-as-markup-preprocessor/out/cjs/index.js?
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36)
```

I have no idea why this is happening...

**Comment by micantoine** [comment]
The issue is coming from the `svelte-as-markup-preprocessor` package where the esm distribution seems to not exist.
I created an issue you can follow https://github.com/firefish5000/svelte-as-markup-preprocessor/issues/1

**Comment by AradAral** [comment]
Thanks. I'll close this issue then.
