### ISSUE TITLE
includePaths should normalize path separator

### ISSUE THREAD

**Issue by ljani** [micantoine/svelte-preprocess-cssmodules#42]
I'm on Windows and tried to configure `includePaths` to only include `["./src"]`, but none of the files match.

If I `console.log(filename, path.resolve(includePath))` [here](https://github.com/micantoine/svelte-preprocess-cssmodules/blob/7c96030363adc8874eac7b15d3aba9c6cb688755/src/lib/requirement.ts#L20), I get the following output:

```text
C:/devel/myblog/src/lib/components/Header.svelte C:\devel\myblog\src
```

Obviously `filename.indexOf` will fail. Thus either `filename` should be normalized to use backslashes or the result from `path.resolve` should be changed to use forward slashes.

PS. maybe consider breaking the [`forEach`](https://github.com/micantoine/svelte-preprocess-cssmodules/blob/7c96030363adc8874eac7b15d3aba9c6cb688755/src/lib/requirement.ts#L19), when the first match is found? Also should [this `if`](https://github.com/micantoine/svelte-preprocess-cssmodules/blob/7c96030363adc8874eac7b15d3aba9c6cb688755/src/lib/requirement.ts#L23) be an `else`?

**Comment by micantoine** [comment]
Included in `v2.1.3`
