### ISSUE TITLE
Usage of `md4` hash type fails in environments using node 17+

### ISSUE THREAD

**Issue by filecage** [micantoine/svelte-preprocess-cssmodules#60]
## Problem Description
As of Node 17, the bundled OpenSSL version has been updated to 3.0. That removes support for a few long discouraged hash alrogithms like `md4` (see https://wiki.openssl.org/index.php/OpenSSL_3.0#Providers).

However, `md4` is your default hash type when generating class name hashes:
https://github.com/micantoine/svelte-preprocess-cssmodules/blob/master/src/lib/getHashDijest.ts#L61

This leads to the build failing with the following error message when using node versions newer than 17:
```
error:0308010C:digital envelope routines::unsupported
```

## Proposed Solution
I assume that changing the default to `md5` should not cause any trouble.

**Comment by filecage** [comment]
Thank you very much!

**Comment by micantoine** [comment]
Also, it is possible to replace the default hash type via the [`localIdentName`](https://github.com/micantoine/svelte-preprocess-cssmodules#localidentname) option using the following pattern `[<hashType>:hash:<digestType>:<length>]`. Not setting the `<hashType>` will fallback to `md5`.

```js
// Preprocess config
...
preprocess: [
  cssModules({
    localIdentName: "[local]-[sha256:hash:base64:6]"
  }),
],
...
```
