### ISSUE TITLE
Is this supposed to support CSS Composition?

### ISSUE THREAD

**Issue by darylteo** [micantoine/svelte-preprocess-cssmodules#81]
https://github.com/css-modules/css-modules#composition

I'm trying to migrate a legacy project using webpack and css modules to svelte and vite. However it doesn't seem like `composes` css rules are being transformed at this point so would like to confirm.

Svelte
```
<style src="./all.css" lang="postcss"></style>

<div class="container"></div>
```

all.css
```
.container {
    composes: reset from "~src/css/styles.css";
    position: relative;
}
```

src/css/styles.css
```
.reset {
    ...
}
```

Expecting

styles.css
```
.container {
    position: relative;
}
```

html
```
<div class="lca-folder-container lca-reset"></div>
```

Got

styles.css
```
.container {
    composes: reset from "~src/css/styles.css";
    position: relative;
}
```

html
```
<div class="lca-folder-container"></div>
```

---

Config

```
import preprocess from 'svelte-preprocess';
import {cssModules, linearPreprocess} from 'svelte-preprocess-cssmodules';

/** @type {import('@sveltejs/kit').Config} */
const config = {
    preprocess: linearPreprocess([
        preprocess.postcss(), // 2 run second
        cssModules({
            useAsDefaultScoping: true,
            includePaths: ['./src'],
            localIdentName: "lca-[folder]-[local]",
        }), // 3 run last
    ]),
}

export default config;
```

Thank you!

**Comment by darylteo** [comment]
Seems I can workaround this by relying on vite to import the css module. 

```
<script>
   import css from "./all.module.css"

   ...
</script>

<div class={css.container}>
</div>
```

But I have to use prop binding instead of just having the class name in there. Funnily enough that's how the legacy app does it (using proto Svelte i.e. Ractive).

**Comment by micantoine** [comment]
Hi @darylteo

`svelte-preprocess-cssmodules` is not using CssModules from https://github.com/css-modules/css-modules. It is just following the same approach and philosophy when using the `native` mode.

As a result, the `composes` rules is not supported.
