### ISSUE TITLE
Syntax error when using keyframes

### ISSUE THREAD

**Issue by icui4cu-web** [micantoine/svelte-preprocess-cssmodules#84]
```
.preloader {
	animation: spin .5s linear infinite;
}
@keyframes spin {
	0% {transform: rotate(0deg);}
	100% {transform: rotate(360deg);}
}
```
turns into
```
._2xDL9mjz7F {
	animation:svelte-s2mqgb-spin .5s linear infinite
}
@keyframes svelte-s2mqgb-spin{
	:global(0%){transform:rotate(0deg)}
	:global(100%){transform:rotate(360deg)}
}
```
As you can see, a `:global(...)` appeared and made the css code not valid
P.S. I use vite for my application (npm create vite@latest myapp -- --template svelte)

**Comment by micantoine** [comment]
Fixed on `v2.2.4`

`keyframes` are also no longer using the svelte scoping but the css module scoping. see #76
